### obtener todos los magos
GET http://localhost:3000/api/magos

### obtener un mago
GET http://localhost:3000/api/magos/6481190f-5832-4946-a1bd-ac2a332b4f6b

### crear un nuevo mago
POST http://localhost:3000/api/magos
Content-Type: application/json

{
    "name": "Hermione",
    "apellido": "Granger",
    "varita": ["Vid","Fibra de Corazon de Dragon","27.3cm"]
}

### modificar un mago (PUT)
PUT http://localhost:3000/api/magos/6481190f-5832-4946-a1bd-ac2a332b4f6b
Content-Type: application/json

{
    "name": "Albus Percival Wulfric Brian",
    "apellido": "Dumbledore",
    "varita": ["Sauco","Pelo de cola de Thestral","38.4cm"]
}

### modificar un mago (PATCH)
PATCH http://localhost:3000/api/magos/6481190f-5832-4946-a1bd-ac2a332b4f6b
Content-Type: application/json

{
    "name": "Albus Brian",
    "varita": ["Sauco","Pelo de cola de Thestral","38.4cm"]
}

### Borrar un mago
DELETE http://localhost:3000/api/magos/6481190f-5832-4946-a1bd-ac2a332b4f6b